version: "3.3"
services: 
  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile
    environment: 
      - PROXY_PASS=web:3000
    ports:
      - 80:80
  mysql:
    image: mysql:8.0
    container_name: product-mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: FWproduct-prj3
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_web
    env_file:
      - .env
    ports:
      - 3000:3000
    links:
      - mysql
    tty: true
    stdin_open: true
    volumes:
      - .:/usr/local/web
      - public-data:/usr/local/web/public
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
volumes:
  public-data:
  mysql-data:
    driver: local